# Generated by Django 3.1.2 on 2020-11-21 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_longitude', models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('destination_latitude', models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('pickup_longitude', models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('pickup_latitude', models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('license_plate', models.CharField(max_length=6, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
