# Generated by Django 3.1.2 on 2020-11-21 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(choices=[('Cor', 'Corolla'), ('Vit', 'Vitz'), ('Yar', 'Yaris'), ('Cad', 'Cadillac'), ('Mer', 'Mercedes'), ('Suz', 'Suzuki'), ('Lif', 'Lifan'), ('For', 'Ford'), ('Kia', 'Kia'), ('BMW', 'BMW'), ('Toy', 'Toyota'), ('Vol', 'Volkswagen'), ('Nis', 'Nissan'), ('Peu', 'Peugeot')], max_length=4)),
                ('is_avaliable', models.BooleanField(default=True)),
                ('license_plate', models.CharField(default=None, max_length=6, unique=True)),
                ('num_of_seats', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)])),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('current_latitude', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('current_longitude', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('previous_latitude', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('previous_longitude', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('is_accepted', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
